### ISSUE TITLE
HTML limitations (length and complexity)

### ISSUE THREAD

**Issue by Utopiah** [supereggbert/aframe-htmlembed-component#4]
I'm probably abusing the component but as I try to display "just text" cf https://fabien.benetou.fr/Portfolio/Portfolio?action=xr I hit a snag and get nothing displayed whereas on a simpler page it works well e.g. https://fabien.benetou.fr/?action=xr . Any page from my wiki now has an ?action=xr to (try to) display it in VR so could be useful to isolate issues.

It might be related to WebGL texture size, could be interesting to clarify the limitations.

**Comment by meizano** [comment]
Try to remove Roboto as font. If there's an element not available inside a tag, all of the code doesn't render.

**Comment by Utopiah** [comment]
Where is Roboto being used?

Here is a simpler page, just text and no external font to download, but quite long yet no output https://fabien.benetou.fr/Site/AllRecentChanges?action=xr

**Comment by supereggbert** [comment]
I think your assessment is correct, it looks like a texture size issue. Not really much I can do about that one except add a warning. With such long content you could just add a scroll. If you surround the content in an overflow hidden with a preset height you can then set a  negative margin on the content to scroll it up.

**Comment by Utopiah** [comment]
Interaction could be problematic (and your suggestions are also great) but even before that, or maybe I missed something, it doesn't display anything at all.

**Comment by supereggbert** [comment]
It does if you limit the height with the overflow hidden, quick scroll example with the content:
http://www.paulbrunt.co.uk/vr/overflowhidden.html

**Comment by Utopiah** [comment]
Oh wow that's great! Thanks for providing such an example with even including scrolling. Then yes I guess a warning when the texture size goes beyond what WebGL (I guess that's the bottleneck) can handle for now?

**Comment by supereggbert** [comment]
No problem
